### PR TITLE
Add support for Swift Package Manager

### PR DESCRIPTION
**Pull request by xezero**
As of Swift 5.3, SPM now supports binary targets so I've created the XCFramework from the original universal framework and specified the binary target in Package.swift

### CODE REVIEW

**Comment by ekimia** [comment]
@xezero thank you for this!!

**Comment by ekimia** [comment]
@xezero its being placed in Plugins as well which is causing an xcode upload to fail

**Comment by xezero** [comment]
@ekimia I'm not really sure why it's also being placed in Plugins. Any thoughts on how to fix it?

**Comment by david-decode** [comment]
@xezero 
Thank you for your contribution. 
We are aware of the rising trend with the SPM and supporting it has already been discussed with the team.
Some work has already been done in this area so keep an eye out for future releases.

David
Shake team

**Pull request closed without merging**
